plugins:
  discourse_news_enabled:
    default: false
    client: true
  discourse_news_source:
    default: "category"
    client: true
    type: enum
    choices:
      - category
      - rss
  discourse_news_category:
    type: category_list
    default: ''
    client: true
  discourse_news_rss:
    default: ''
  discourse_news_icon:
    default: ''
    client: true
  discourse_news_title_below_image:
    default: false
    client: true
  discourse_news_show_reply_count:
    default: false
    client: true
  discourse_news_sort:
    type: enum
    default: "bumped_at"
    choices:
      - bumped_at
      - created_at
  discourse_news_sidebar_topic_list:
    default: true
    client: true
  discourse_news_sidebar_topic_list_filter:
    default: 'latest'
    client: true
  discourse_news_sidebar_topic_list_limit:
    default: 10
    client: true
